Media exercise
kely-rufino/BootcampSpaBath pull request #2
Opened 2021-11-05 13:47 UTC by kely-rufino

Hello,
I called the project "4 Cards" of the Mobile Display.

2021-11-05 15:45 UTC, asjoss commented on MobileDisplay.css
> +        flex-direction: column;
Is the reason we don't add display: flex in here is because it's inherited from the original .container entry above?

2021-11-05 15:49 UTC, asjoss commented on MobileDisplay.html
> +                        <path fill="#676E74" d="M26.375 52.625h11.25V64h-11.25z"/>
did all those <path> tags add in automatically for the images?

2021-11-05 20:06 UTC, kely-rufino commented on MobileDisplay.css
> +        flex-direction: column;
Yes, it is. 😊

2021-11-05 20:07 UTC, kely-rufino commented on MobileDisplay.html
> +                        <path fill="#676E74" d="M26.375 52.625h11.25V64h-11.25z"/>
Yes, I couldn't think about put shorter. I will make it short.

2021-11-06 11:51 UTC, Callum-Xavi commented
CSS code looks nice and tidy!

2021-11-06 12:00 UTC, abulyousuf requested changes
Pretty good work! It works fine with mobile and desktop views. Just need to link or import Google Fonts, otherwise change to browser default fonts.

But one thing, the left card is not fully shown on iPad Pro view.

2021-11-06 13:05 UTC, kely-rufino commented on MobileDisplay.css
> +    font-family: "Roboto Light";
Ah! thanks!  I will do this.

2021-11-06 13:11 UTC, merged